config/routes.rb
Luckypots::Application.routes.draw do
  get '/admin', to: 'keywords#admin'
  resources :potlucks
  resources :keywords
  resources :items

  root :to => 'potlucks#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :tags
  # attr_accessible :name
  belongs_to :potluck
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_and_belongs_to_many :potlucks
end

app/models/potluck.rb
class Potluck < ActiveRecord::Base
  has_many :tags
  has_many :items
  has_and_belongs_to_many :keywords
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  # attr_accessible :name
  has_and_belongs_to_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def show
		Sleep 1
    @item = Item.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @item = Item.new

		respond_to do |format|
	    format.html # new.html.erb
	    format.js
	  end
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to :back, notice: 'Item was successfully created.' }
        format.js
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update_attributes(params[:recipe])
      redirect_to "/items/index"
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to "/items/index"
  end

  def index
    @items = Item.all
    @item = Item.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def item_params
    params.require(:item).permit(:name, :potluck_id)
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController

  def admin
    @tags = Tag.all
    @potlucks = Potluck.all
    @keywords = Keyword.all
    @items = Item.all
    @keyword = Keyword.new
  end

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new(keyword_params)

    if @keyword.save
      redirect_to "/admin"
    else
      render :new
    end
  end

  def keyword_params
    # This allows attributes to be saved to writing (rails 4 change)
    params.require(:keyword).permit(:name)
  end

  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to "/admin" }
      format.json { head :no_content }
    end
  end
end

app/controllers/potlucks_controller.rb
class PotlucksController < ApplicationController
  def show
    @potluck = Potluck.find(params[:id])
    @items = Item.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @potluck = Potluck.new
  end

  def create
    @potluck = Potluck.new(potluck_params)

    if @potluck.save
      redirect_to potluck_path(@potluck.id)
    else
      render :new
    end
  end

  def edit
    @potluck = Potluck.find(params[:id])
  end

  def update
    @potluck = Potluck.find(params[:id])

    if @potluck.update_attributes(params[:recipe])
      redirect_to "/potlucks/index"
    else
      render :edit
    end
  end

  def destroy
    @potluck = Potluck.find(params[:id])
    @potluck.destroy
    redirect_to "/potlucks/index"
  end

  def index
    @potlucks = Potluck.all
    @keywords = Keyword.all
    @potluck = Potluck.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def potluck_params
    params.require(:potluck).permit(:datetime, :location, :name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to "admin"
    else
      render :new
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update_attributes(params[:recipe])
      redirect_to "/admin"
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to "/admin"
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/potluck_helper.rb
module PotluckHelper
end

app/helpers/potlucks_helper.rb
module PotlucksHelper
	require 'instagram'

	CALLBACK_URL = "http://localhost:4567/oauth/callback"

	Instagram.configure do |config|
	  config.client_id = ENV['INSTACLIENTID']
	  config.client_secret = ENV['INSTACLIENTSECRET']
	end

	def get_potluck_pictures
	  results = Instagram.tag_recent_media("potluck")
	  results_array = []
	  while results_array.length < 26
	    results.each do |image|
	      url = image.images.thumbnail.url

	        results_array << url
	    end

	    max_id = results.last.id
	    results = Instagram.tag_recent_media("potluck", options = {max_id:max_id})
	  end
	  return results_array
	end

	def get_singles_photos
		results = Instagram.tag_recent_media("selfie")
	  results_array = []
	  while results_array.length < 26
	    results.each do |image|
	      url = image.images.thumbnail.url
	        results_array << url
	    end

	    max_id = results.last.id
	    results = Instagram.tag_recent_media("selfie", options = {max_id:max_id})
	  end
	  return results_array
	end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/items/create.js.erb
// $('#refresh_items').click(function() {

//  $(this).closest('form').find("input[type=text]").val("");
//  $('#items_table').empty().html("<%= j render(partial: 'potlucks/items_table') %>");


// });

app/views/keywords/admin.html.erb
<div class="row">
  <div class="medium-8 columns medium-centered">

      <h3 class="luckypot">Item Tags</h3>
      <a href="new_tag" class="button small">New Item tag</a><br><br>
      <ul>
        <% @tags.each do |tag| %>
          <li>
            <strong><%= tag.name %></strong> <a href="/edit_tag/<%= tag.id %>">Edit</a>
          </li>
        <% end %>
      </ul>

      <h3 class="luckypot">Potluck Keyword</h3>
      <a href="#" data-reveal-id="keywordModal" class="button small">New Potluck Keyword</a><br><br>
      <ul>
        <% @keywords.each do |keyword| %>
          <li>
            <strong><%= keyword.name %></strong> <a href="/edit_keyword/<%= keyword.id %>">Edit</a>
            <a href="/keywords/<%= keyword.id %>" data-method="delete" rel="nofollow">Delete</a>
          </li>
        <% end %>
      </ul>

      <h3 class="luckypot">All Items</h3>
      <a href="new_item" class="button small">New Item</a><br><br>
      <ul>
        <% @items.each do |item| %>
          <li>
            <strong><%= item.name %></strong> <a href="/edit_item/<%= item.id %>">Edit</a> tags: <%= item.tags.map {|tag| tag.name }.join(", ") %> at potluck: <%= (item.potluck.name if item.potluck) %> and brought by <#%= (item.person.name if item.person) %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>

  <div id="keywordModal" class="reveal-modal" data-reveal>
    <%= form_for(@keyword, html: {"data-abide" => ""}) do |f| %>
      <h1>Enter Potluck Keyword</h1>
      <div>
        <%= f.text_area :name, :required => "" %>
        <small class="error">You must write in the box.</small>
      </div><br>
      <div>
        <%= f.submit "Save", class: 'button submit' %>
      </div>
    <% end %>
  </div>

app/views/keywords/new.html.erb
<div class="row">
  <div class="large-6 columns large-centered">
    <h2 class="luckypot">Add a new potluck keyword:</h2>
    <form method="post" action="/new_keyword">
      Tag:
      <input type="text" name="keyword[name]">
      <button class="button small">Save Keyword</button>
    </form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Luckypots</title>
  <link href='http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Oleo+Script:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="fixed">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1 class="luckypot"><a href="/">Lucky Pots</a></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
      </ul>
      <section class="top-bar-section">
        <!-- Left Nav Section -->
        <ul class="left">
          <li class="divider"></li>
          <li class="active"><a href="/">Potlucks</a></li>
          <li class="divider"></li>
          <li><a href="/admin">Admin</a></li>
          <li class="divider"></li>
        </ul>
        <ul class="right">
          <!-- To be replaced by login/logout -->
          <li> <img class="profilePic" src="https://graph.facebook.com/yekaterina/picture">;</li>
        </ul>
      </section>
    </nav>
  </div>

  <div class="container">
    <%= yield %>
  </div>

<script>
  $(document).foundation();
</script>

</body>
</html>

app/views/potlucks/_items_table.erb
<table>
  <thead>
    <tr>
      <th>Item</th>
      <!-- <th>Tags</th> -->
      <th>Assigned?</th>
<!--           <th></th>
-->        </tr>
  </thead>
  <tbody>
    <tr>
      <% @potluck.items.each do |item| %>
      <td><%= item.name %></td>
      <!-- <td><%= item.tags.map {|tag| tag.name }.join(", ") %></td> -->
      <td>
      <a href="/item_assign/<%=item.id%>">Claim</a></td>
<!--           <td><a href="/edit_item/<%= item.id %>">Edit</a></td>
-->        </tr><% end %>
  </tbody>
</table>

app/views/potlucks/create.html.erb
<h1>Potluck#create</h1>
<p>Find me in app/views/potluck/create.html.erb</p>

app/views/potlucks/edit.html.erb
<h1>Potluck#edit</h1>
<p>Find me in app/views/potluck/edit.html.erb</p>

app/views/potlucks/index.html.erb
<div>
  <ul class="large-block-grid-8" id="photoBlock">
    <% get_potluck_pictures.first(16).each do |picture| %>
    <li><img src="<%=picture%>"></li>
    <% end %>
  </ul>
</div>
<div class="row">
  <div class="medium-8 columns medium-centered">
        <!-- form for new potluck. -->
    <div id="potluckForm">
      <%= form_for :potluck do |f| %>
      <h2>New Potluck</h2>
        <%= f.label :name %>
        <%= f.text_field :name%>
        <%= f.label :location %>
        <%= f.text_field :location %>
        <%= f.label :datetime %>
        <%= f.datetime_local_field :datetime %> 
        <%= f.collection_check_boxes :keyword_ids, Keyword.all, :id, :name %>
        <%= f.button :submit, id: "submitPotluck" %>
      <% end %>
    </div>

    <h3 class="luckypot">Upcoming Potlucks</h3>
    <button id="newPotluck" class="button">Plan a Potluck</button>
    <div class="potluckList">
    <ul>
      <% @potlucks.each do |potluck| %>
      <li>
        <strong><a href="/potlucks/<%= potluck.id %>"><%= potluck.name %></a></strong> on <%= potluck.datetime.strftime("%A, %b %d, %Y at %I:%M%p") %> at <%= potluck.location %> <a href="/edit_potluck/<%= potluck.id %>">Edit</a>
      </li>
      <% end %>
    </ul>
  </div>
  </div>
</div>

app/views/potlucks/new.html.erb
<div class="row">
  <div class="large-6 columns large-centered">
    <h2 class="luckypot">Create your Potluck</h2>
    <form method="post" action="/new_potluck">
      Potluck Name:
      <input type="text" name="potluck[name]"><br>
      Potluck Location:
      <input type="text" name="potluck[location]"><br>
      Potluck Date:
      <input type="date" name="potluck[datetime]"><br><br>

      <button class="button success small">Save Potluck</button>
    </form>
  </div>
</div>

app/views/potlucks/refresh_items.js.erb
console.log("hello")

$('#items_table').empty().html("<%= j render :partial => 'items_table' %>");

app/views/potlucks/show.html.erb
<div class="row">
  <div class="medium-8 columns medium-centered">
    <h2 class="luckypot"><%= @potluck.name %></h2>
    <div>
      <ul class="medium-block-grid-4" id="peopleBlock">
        <% get_singles_photos.first(8).each do |picture| %>
        <li><img src="<%=picture%>"></li>
        <% end %>
      </ul>
    </div>

    <div>
      <ul>
        <p><em><%= @potluck.keywords.map {|keyword| keyword.name }.join(" - ") %></em></p>
      </ul>
      <h4>Location: <%= @potluck.location %></h4>
      <h4>Date: <%= @potluck.datetime.strftime("%A, %b %d, %Y at %I:%M%p") %>
      </h4>
      <button id="newItem" class="button">Add Item</button>
    </div>

    <div id="itemForm">
      <%= form_for Item.new, :remote => true do |f| %>
      <h2>Add Item</h2>
        <%= f.label :item %>
        <%= f.text_field :name %>
        <%= f.hidden_field :potluck_id, :value => @potluck.id %>
        <%= f.button :submit, :id => "refresh_items" %>
      <% end %>

      
<!-- Tags are not currently set up -->
        <% Tag.all.each do |tag| %>
            <input type="checkbox"
            name="item[tag_ids][]" id="checkbox" value="<%=tag.id%>"><%= tag.name %>
              <br>
            <% end %>
      </form>
    </div>

    <div id="items_table">
      <%= render "items_table" %>
    </div>

  </div>
</div>